//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B_Shop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class bshopdbEntities : DbContext
    {
        public bshopdbEntities()
            : base("name=bshopdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblbranch> tblbranches { get; set; }
        public DbSet<tblinventory> tblinventories { get; set; }
        public DbSet<tblorder> tblorders { get; set; }
    
        public virtual int ADD_NEW_ITEM(string pDescription, Nullable<decimal> pPrice, Nullable<int> pQuantity, string pCategory, Nullable<int> pBranchID)
        {
            var pDescriptionParameter = pDescription != null ?
                new ObjectParameter("pDescription", pDescription) :
                new ObjectParameter("pDescription", typeof(string));
    
            var pPriceParameter = pPrice.HasValue ?
                new ObjectParameter("pPrice", pPrice) :
                new ObjectParameter("pPrice", typeof(decimal));
    
            var pQuantityParameter = pQuantity.HasValue ?
                new ObjectParameter("pQuantity", pQuantity) :
                new ObjectParameter("pQuantity", typeof(int));
    
            var pCategoryParameter = pCategory != null ?
                new ObjectParameter("pCategory", pCategory) :
                new ObjectParameter("pCategory", typeof(string));
    
            var pBranchIDParameter = pBranchID.HasValue ?
                new ObjectParameter("pBranchID", pBranchID) :
                new ObjectParameter("pBranchID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_NEW_ITEM", pDescriptionParameter, pPriceParameter, pQuantityParameter, pCategoryParameter, pBranchIDParameter);
        }
    
        public virtual int CREATE_B_SHOP_DB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CREATE_B_SHOP_DB");
        }
    
        public virtual int ADD_NEW_CLOTHING(string pDescription, Nullable<decimal> pPrice, Nullable<int> pQuantity, string pCategory, Nullable<int> pBranchID, Nullable<int> pSize, string pGender)
        {
            var pDescriptionParameter = pDescription != null ?
                new ObjectParameter("pDescription", pDescription) :
                new ObjectParameter("pDescription", typeof(string));
    
            var pPriceParameter = pPrice.HasValue ?
                new ObjectParameter("pPrice", pPrice) :
                new ObjectParameter("pPrice", typeof(decimal));
    
            var pQuantityParameter = pQuantity.HasValue ?
                new ObjectParameter("pQuantity", pQuantity) :
                new ObjectParameter("pQuantity", typeof(int));
    
            var pCategoryParameter = pCategory != null ?
                new ObjectParameter("pCategory", pCategory) :
                new ObjectParameter("pCategory", typeof(string));
    
            var pBranchIDParameter = pBranchID.HasValue ?
                new ObjectParameter("pBranchID", pBranchID) :
                new ObjectParameter("pBranchID", typeof(int));
    
            var pSizeParameter = pSize.HasValue ?
                new ObjectParameter("pSize", pSize) :
                new ObjectParameter("pSize", typeof(int));
    
            var pGenderParameter = pGender != null ?
                new ObjectParameter("pGender", pGender) :
                new ObjectParameter("pGender", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_NEW_CLOTHING", pDescriptionParameter, pPriceParameter, pQuantityParameter, pCategoryParameter, pBranchIDParameter, pSizeParameter, pGenderParameter);
        }
    
        public virtual int ADD_NEW_FURNITURE(string pDescription, Nullable<decimal> pPrice, Nullable<int> pQuantity, string pCategory, Nullable<int> pBranchID, Nullable<decimal> pWeight, Nullable<int> pNumParts)
        {
            var pDescriptionParameter = pDescription != null ?
                new ObjectParameter("pDescription", pDescription) :
                new ObjectParameter("pDescription", typeof(string));
    
            var pPriceParameter = pPrice.HasValue ?
                new ObjectParameter("pPrice", pPrice) :
                new ObjectParameter("pPrice", typeof(decimal));
    
            var pQuantityParameter = pQuantity.HasValue ?
                new ObjectParameter("pQuantity", pQuantity) :
                new ObjectParameter("pQuantity", typeof(int));
    
            var pCategoryParameter = pCategory != null ?
                new ObjectParameter("pCategory", pCategory) :
                new ObjectParameter("pCategory", typeof(string));
    
            var pBranchIDParameter = pBranchID.HasValue ?
                new ObjectParameter("pBranchID", pBranchID) :
                new ObjectParameter("pBranchID", typeof(int));
    
            var pWeightParameter = pWeight.HasValue ?
                new ObjectParameter("pWeight", pWeight) :
                new ObjectParameter("pWeight", typeof(decimal));
    
            var pNumPartsParameter = pNumParts.HasValue ?
                new ObjectParameter("pNumParts", pNumParts) :
                new ObjectParameter("pNumParts", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_NEW_FURNITURE", pDescriptionParameter, pPriceParameter, pQuantityParameter, pCategoryParameter, pBranchIDParameter, pWeightParameter, pNumPartsParameter);
        }
    }
}
