//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B_Shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbranch
    {
        public tblbranch()
        {
            this.tblinventories = new HashSet<tblinventory>();
        }
    
        public int branchID { get; set; }
        public string branchName { get; set; }
        public string branchAddress { get; set; }
        public string branchPhone { get; set; }
    
        public virtual ICollection<tblinventory> tblinventories { get; set; }
    }
}
